version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DB_DOCKER_PORT
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    container_name: carassistant_app
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: unless-stopped
    image: carassistant
    build: .
    env_file: ./.env
    ports:
      - "8080:$PORT"  # Зв'язуємо порт 8080 на хості з портом, визначеним у змінній PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_PROFILES_ACTIVE: render  # Активуємо профіль для Render
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQL_DB_DOCKER_PORT/$MYSQLDB_DATABASE?serverTimezone=UTC",
          "spring.datasource.username" : "$MYSQLDB_USER",
          "spring.datasource.password" : "$MYSQLDB_PASSWORD",
          "spring.jpa.hibernate.ddl-auto" : "update",
          "spring.jpa.show-sql" : "true",
          "jwt.expiration" : "$JWT_EXPIRATION_TIME",
          "jwt.secret" : "$JWT_SECRET"
        }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      PORT: 8080  # Встановлюємо порт для сервісу
volumes:
  mysql_data:
